### ISSUE TITLE
If url in FileBox.fromUrl() is very long, the file.name will be long too, and then we can not save it with this name.

### ISSUE THREAD

**Issue by su-chang** [huan/file-box#23]
If user does not provide name parameter for `fromUrl()` when they use a long url, like this example:
```js
FileBox.fromUrl('http://siyouyunsy-1253559996.cos.ap-guangzhou.myqcloud.com/msg/0FAPG/20191225/8792756920681108584_wxid_orp7dihe2pm112_1577258245436_.png?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKIDBi7d3I4UK7iDXkAhQyQsDMNGxY2KmlCY%26q-sign-time%3D1577258245%3B1663571845%26q-key-time%3D1577258245%3B1663571845%26q-header-list%3D%26q-url-param-list%3D%26q-signature%3De459d0f7045da0e7e8a21e06f31a583c0a2153c8')
```

The name will generated by
```js
const parsedUrl = nodePath.parse(url)
name = parsedUrl.base
```
Name will be a long string and will make some mistakes, do we have some best practices for it?

- make a warn log
- extract file name

**Comment by huan** [comment]
I believe the best practice is to always provide the name parameter for `fromUrl(, name)` to prevent this kind of problem, or use a file name with `toFile()` to enforce a filename.

**Comment by su-chang** [comment]
Understand and thank you for your quick response.

**Comment by huan** [comment]
You are welcome.
