### ISSUE TITLE
FileBox.fromUrl()这个api 我尝试 在wecharty（nodejs版本）中发送视频，

### ISSUE THREAD

**Issue by xiebiaokmy** [huan/file-box#40]
我阅读相关文档之后按照发送在线图片的方式来发送视频消息（因为没有找到示例），项目总是报错 Cannot find ffmpeg ,安装对应依赖之后还是不行，请问是我使用的方式不对吗？

**Comment by EvynXu** [comment]
最后是怎么解决的呢，遇到同样的报错
