### ISSUE TITLE
add optional md5 property for local files

### ISSUE THREAD

**Issue by hcfw007** [huan/file-box#74]
File-Boxes are often used to transfer files between devices, thus if we can compute the md5 when packing a local file into file-box object, it would make the remote receiver much more convenient.
It could decide whether its's a duplicated file or not to decide the necessity to download it. It can check if it's the right file which the sender packed.

I'll propose a draft pr asap.

- [x] always let user to pass md5 string when create a file-box so that the receiver can check the file with md5

#75

**Comment by windmemory** [comment]
Could you please also share a draft design for this feature?

**Comment by hcfw007** [comment]
question:
1. do we need to add md5 property for other FileBox.From factories that does not take an object?
2. do we need to compute md5 for stream and buffer? I'm not sure whether we can do that or not.

**Comment by huan** [comment]
Your PR has answered your own questions already, I think it's good to leave the md5 calculating task to the end-user.

**Comment by hcfw007** [comment]
Mission accomplished. Cheers.
