### ISSUE TITLE
How to deal with the problem `Error: certificate has expired`

### ISSUE THREAD

**Issue by fabian4** [huan/file-box#76]
It is the problem I have met when I am trying to get an image from a remote url
~~~shell
Error: certificate has expired
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket.emit (node:domain:475:12)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
  code: 'CERT_HAS_EXPIRED'
}
~~~
I can download it with my browser successfully but can not get it throught filebox
Thanks for your time ！

**Comment by huan** [comment]
Could you please provide a reproducible code for it?

**Comment by fabian4** [comment]
~~~ts
FileBox.fromUrl('https://gateway.5g-msg.com:30083/UP/7a90a4a8-f6ab-442e-a777-c5b3fa689e15.vcf')
~~~

It may caused by the domain's certificate, but is there any way to avoid it

**Comment by huan** [comment]
```
Your connection is not private
Attackers might be trying to steal your information from gateway.5g-msg.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID
To get Chrome’s highest level of security, turn on enhanced protection
```

> It may be caused by the domain's certificate, but is there any way to avoid it

Obviously, it was caused by an invalid TLS CA.

We can not process an invalid CA for security reasons unless you disable the whole Node.js TLS, which is not recommended.

**Comment by fabian4** [comment]
Thanks a lot !
